WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5141ca0af0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/fastparquet/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5141ca0e20>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/fastparquet/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5141ca0fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/fastparquet/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5141c491c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/fastparquet/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5141c49370>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/fastparquet/
ERROR: Could not find a version that satisfies the requirement fastparquet (from versions: none)
ERROR: No matching distribution found for fastparquet
